vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: '%post_directory%'
            upload_destination: '%kernel.project_dir%/public/assets/Images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: false
            delete_on_update: false